config/routes.rb
Rails.application.routes.draw do
  devise_for :admins

  resources :users
  resources :teams
  resources :roles
  resources :projects
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "projects#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: true, format: { with: /\A\w+\z/, message: 'can only contain alphanumeric characters' }
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: 'is not a valid email address' }
  validates :password, presence: true, length: { minimum: 6 }, confirmation: true

  has_many :users
  has_many :teams
  has_many :roles

  attr_accessor :login

  def self.find_for_authentication(conditions)
    login = conditions.delete(:login)
    where(conditions).where(["username = :value OR email = :value", { :value => login }]).first
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles
  has_many :users, through: :user_roles
  belongs_to :admin
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :project
end

app/models/team.rb
class Team < ApplicationRecord
  belongs_to :admin

  has_many :team_memberships
  has_many :users, through: :team_memberships
  accepts_nested_attributes_for :team_memberships, allow_destroy: true
end

app/models/team_membership.rb
class TeamMembership < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/user.rb
class User < ApplicationRecord

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: true, format: { with: /\A\w+\z/, message: 'can only contain alphanumeric characters' }
  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: 'is not a valid email address' }
  validates :password_digest, presence: true, length: { minimum: 6 }, confirmation: true
  
  has_many :team_memberships
  has_many :teams, through: :team_memberships
  accepts_nested_attributes_for :team_memberships, allow_destroy: true

  has_many :user_roles
  has_many :roles, through: :user_roles    
  belongs_to :admin  
  
  accepts_nested_attributes_for :user_roles

end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :email, :password])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def new
    @project = Project.new
    @project.tasks.build
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path, notice: "Project was successfully created"
    else
      render :new
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, tasks_attributes: [:id, :name, :_destroy])
  end
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_current_admin

  def index
    @roles = @admin.roles.all
  end

  def new
    @role = Role.new
  end

  def create
    @role = @admin.roles.new(role_params)
    if @role.save
      redirect_to roles_path, notice: 'Role was successfully created.'
    else
      render :new
    end
  end

  def edit
    @role = @admin.roles.find(params[:id])
  end

  def update
    @role = @admin.roles.find(params[:id])
    if @role.update(role_params)
      redirect_to roles_path, notice: 'Role was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @role = @admin.roles.find(params[:id])
    @role.destroy
    redirect_to roles_path, notice: 'Role was successfully destroyed.'
  end

  private

  def role_params
    params.require(:role).permit(:name, :description)
  end

  def set_current_admin
    @admin = current_admin
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_current_admin

  def index
    @teams = @admin.teams.all
  end

  def new
    @team = @admin.teams.new
    @team.team_memberships.build
  end

  def create
    @team = @admin.teams.new(team_params)
    if @team.save
      redirect_to teams_path, notice: 'Team was successfully created.'
    else
      render :new
    end
  end

  def show
    @usr = @admin.users.find(params[:id])
  end

  def edit
    @team = @admin.teams.find(params[:id])
    @team.team_memberships.build if @team.team_memberships.empty?
  end

  def update
    @team = @admin.teams.find(params[:id])
    if @team.update(team_params)
      redirect_to teams_path, notice: 'Team was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @team = @admin.teams.find(params[:id])
    @team.destroy
    redirect_to teams_path, notice: 'Team was successfully destroyed.'
  end

  private

  def team_params
    params.require(:team).permit(:name, :description, team_memberships_attributes: [:id, :user_id, :_destroy])
  end

  def set_current_admin
    @admin = current_admin
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_current_admin

  def index
    @users = @admin.users.all
  end

  def new
    @user = @admin.users.new
    @user.user_roles.build
    @user.team_memberships.build
    @teams = Team.all
  end

  def create
    @user = @admin.users.new(user_params)
    if @user.save
      redirect_to users_path, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def show
    @user = @admin.users.find(params[:id])
  end


  def edit
    @user = @admin.users.find(params[:id])
    @user.team_memberships.build if @user.team_memberships.empty?
    @user.user_roles.build if @user.user_roles.empty?
  end

  def update
    @user = @admin.users.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @user = @admin.users.find(params[:id])
    @user.destroy
    redirect_to users_path, notice: 'User was successfully destroyed.'
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :username, :email, :password_digest, team_memberships_attributes: [:id, :team_id, :_destroy], user_roles_attributes: [:id, :role_id, :_destroy])
  end

  def set_current_admin
    @admin = current_admin
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projects/_form.html.erb
<h1>Field Form</h1>
<%= form_with(model: @project, html: { novalidate: true }, data: { controller: 'form', target: "form.form", action: 'submit->form#formSubmit' }) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true %>
  </div>
  <div>
    <%= f.fields_for :tasks do |task_form| %>
      <%= render "task_fields", f: task_form %>
    <% end %>
    <%= link_to_add_fields "Add Task", f, :tasks %>
  </div>

  <div class="clipboard-button">
    <p>Not Good</p>
  </div>
<!--  <div>-->
    <%#= button_tag "Greet", data: {} %>
<!--  </div>-->
<!--  <input data-projects-target="email" type="email">-->
<!--  <button data-action="projects#greet">Greet</button>-->


  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/_task_fields.html.erb
<fieldset>
  <%= f.label :name, "Task Name" %>
  <%= f.text_field :name %>
  <%= f.hidden_field :_destroy %>
  <%#= f.label :_destroy, "Remove Task", class: 'remove_fields' %>
  <%= link_to "Remove Task", "#", class: 'remove_field', data: { action: "form#deleteRow"} %>

  <div data-controller="form" data-form-show-if-value="human">
    <select data-form-target="input" value="human" data-action="change->form#toggle">
      <option value=""></option>
      <option value="human" selected>human</option>
      <option value="animal">animal</option>
    </select>
    <div data-form-target="output" hidden="">
      an output if human
    </div>
  </div>

</fieldset>

app/views/projects/index.html.erb
<h1>Projects List</h1>
<table class="border rounded-lg shadow-md w-full">
  <thead>
    <tr>
      <th class="px-4 py-2 bg-gray-800 text-white font-semibold border border-gray-600">Project Name</th>
      <th class="px-4 py-2 bg-gray-800 text-white font-semibold border border-gray-600">Tasks Name</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td class=" px-4 py-2 border border-gray-600"><%= project.name %></td>
<!--        <td class=" px-4 py-2 border border-gray-600"><%#= project.tasks.first.name %></td>-->
      </tr>
    <% end %>

  </tbody>
</table>

<%= link_to "New Project", new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render "form"  %>

app/views/roles/_form.html.haml
= form_with(model: @role) do |form|
  - if @role.errors.any?
    #error_explanation
      %h2= "#{pluralize(@role.errors.count, 'error')} prohibited this role from being saved:"
      %ul
        - @role.errors.full_messages.each do |msg|
          %li= msg

  .field
    = form.label :name
    = form.text_field :name, required: true

  .field
    = form.label :description
    = form.text_field :description, required: true

  .actions
    = form.submit 'Save'

app/views/roles/edit.html.haml
%h1 Editing Role

= render 'form'

= link_to 'Back', roles_path

app/views/roles/index.html.haml
%h1 Roles List

%table.border.rounded-lg.shadow-md.w-full
  %thead
    %tr
      %th.px-4.py-2.bg-gray-800.text-white.font-semibold.border.border-gray-600
        Name
      %th.px-4.py-2.bg-gray-800.text-white.font-semibold.border.border-gray-600
        Description
      %th.px-4.py-2.bg-gray-800.text-white.font-semibold.border.border-gray-600
        Edit
      %th.px-4.py-2.bg-gray-800.text-white.font-semibold.border.border-gray-600
        Delete  
        
  %tbody
    - @roles.each do |role|
      %tr
        %td.px-4.py-2.border.border-gray-600
          = role.name
        %td.px-4.py-2.border.border-gray-600
          = role.description
        %td.px-4.py-2.border.border-gray-600
          = link_to 'Edit', edit_role_path(role)
        %td.px-4.py-2.border.border-gray-600
          = link_to 'Destroy', role, method: :delete, data: { confirm: 'Are you sure?' }
  
= link_to 'New Role', new_role_path

app/views/roles/new.html.haml
%h1 New Role

= render 'form'

= link_to 'Back', roles_path

app/views/users/_fields.html.haml
.nested-fields
  = form.label :team_id, 'Select Team:'
  = form.collection_select :team_id, @teams, :id, :name, { include_blank: 'No team' }
  = link_to_remove_association 'Remove', form

app/views/users/_form.html.haml
= form_with(model: @user, local: true) do |form|
  - if @user.errors.any?
    #error_explanation
      %h2= "#{pluralize(@user.errors.count, 'error')} prohibited this user from being saved:"
      %ul
        - @user.errors.full_messages.each do |msg|
          %li= msg

  .field
    = form.label :first_name
    = form.text_field :first_name, required: true

  .field
    = form.label :last_name
    = form.text_field :last_name, required: true

  .field
    = form.label :username
    = form.text_field :username, required: true

  .field
    = form.fields_for :user_roles do |role_form|
      = role_form.label :name, "Role"
      = role_form.collection_select :role_id, Role.all, :id, :name, include_blank: true

  .field
    = form.fields_for :team_memberships do |role_form|
      = role_form.label :name, "Team"
      = role_form.collection_select :team_id, Team.all, :id, :name, include_blank: true   

  .field
    = form.label :email
    = form.email_field :email, required: true

  .field
    = form.label :password_digest
    = form.password_field :password_digest, required: true

  .actions
    = form.submit 'Save'

app/views/users/edit.html.haml
%h1 Editing User

= render 'form'

= link_to 'Back', users_path

app/views/users/index.html.haml
%h1 Users List
  
= link_to 'New User link 2', new_user_path

%hr
%div.flex.flex-row
  %ul.flex.flex-row
    %li
      = link_to "Users", users_path
    %li
      = link_to "Roles", roles_path
    %li
      = link_to "Teams", teams_path     

%hr
%table.border.rounded-lg.shadow-md.w-full
  %thead
    %tr
      %th.px-4.py-2.bg-gray-800.text-white.font-semibold.border.border-gray-600
        First Name
      %th.px-4.py-2.bg-gray-800.text-white.font-semibold.border.border-gray-600
        Last Name
      %th.px-4.py-2.bg-gray-800.text-white.font-semibold.border.border-gray-600
        Username
      %th.px-4.py-2.bg-gray-800.text-white.font-semibold.border.border-gray-600
        Email
      %th.px-4.py-2.bg-gray-800.text-white.font-semibold.border.border-gray-600
        Edit
      %th.px-4.py-2.bg-gray-800.text-white.font-semibold.border.border-gray-600
        Delete
        
  %tbody
    - @users.each do |user|
      %tr
        %td.px-4.py-2.border.border-gray-600
          = user.first_name
        %td.px-4.py-2.border.border-gray-600
          = user.last_name
        %td.px-4.py-2.border.border-gray-600
          = user.username
        %td.px-4.py-2.border.border-gray-600
          = user.email
        %td.px-4.py-2.border.border-gray-600
          = link_to 'Edit', edit_user_path(user)
        %td.px-4.py-2.border.border-gray-600
          = link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } 

app/views/users/new.html.haml
%h1 New User

= render 'form'

= link_to 'Back', users_path